[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Trabalho_RI"
version = "0.1.0"
authors = [{ name = "Arthur Matias", email = "arthur.matias@icomp.ufam.edu.br" },{ name = "Bianka Vasconcelos", email = "" }]
description = "O melhor trabalho de RI do meu bairro"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "elasticsearch",
]

